# configuration parsing starts here
defaults:
  - _self_
  - experiment: mineworld_bc_train # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: mineworld_frames # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: vpt_bc_1x # algorithm yaml file name in configurations/algorithm folder [fixme]
  - optional dataset_experiment: ${dataset}_${experiment} # optional yaml file in configurations/dataset_experiment folder, overrides algorithm and experiment configurations that are dataset and experiment dependent
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

name: default
debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: williamgao110-harvard-university # wandb account name / organization name [fixme]
  project: dfot # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: online # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wanmdb run id containing checkpoint or a path to a checkpoint file 
